version: "3.8"
services:
  client:
    build: ./client
    restart: always
    ports:
      - 80:80
    depends_on:
      - userservice
      - libraryservice
      - fashionservice
  userservice:
    build: ./userservice
    restart: always
    environment:
      MONGO_HOST: mongo
      MONGO_USER: root
      MONGO_PASS: example
    ports:
      - 3001:3000
    depends_on:
      - mongo
  fashionservice:
    build: ./fashionservice
    restart: always
    ports:
      - 8000:8000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  libraryservice:
    build: ./libraryservice
    restart: always
    ports:
      - 8080:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: library
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
  robottests:
    build: ./robotTests
    volumes:
      - ./robotTests:/robotframework/tests
      - ./robotTests/reports:/robotframework/logs
