version: "3.8"
services:
  userservice:
    build: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 3001:3000
    command: ["npm", "run-script", "start-dev"]
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
