version: "3.8"
services:
  libraryservice:
    image: maven:3-jdk-14
    working_dir: /usr/src/mymaven
    volumes:
      - .:/usr/src/mymaven
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - adminer
  postgres:
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: library
  adminer:
    image: adminer
    ports:
      - 8082:8080
